// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! # Configuration Utility Functions
//!
//! Provides configuration-related utility functions through focused modules
//! for interpolation and structured serde conversion.

#[cfg(any(feature = "toml", feature = "yaml"))]
use std::collections::HashSet;

use qubit_value::ValueError;

use super::ConfigError;
use super::ConfigResult;

#[path = "utils/interpolation.rs"]
mod interpolation;
#[path = "utils/structured_serde.rs"]
mod structured_serde;

pub(crate) use interpolation::substitute_variables_with_fallback;
pub(crate) use structured_serde::insert_deserialize_value;
pub(crate) use structured_serde::prepare_deserialize_value;

/// Maps a [`ValueError`] from typed property access to [`ConfigError`], using
/// `key` as the configuration path for type and conversion errors.
pub(crate) fn map_value_error(key: &str, err: ValueError) -> ConfigError {
    ConfigError::from((key, err))
}

/// Validates a key generated by source-specific normalization.
pub(crate) fn validate_normalized_config_key(key: &str, origin: &str) -> ConfigResult<()> {
    if key.is_empty() {
        return Err(ConfigError::KeyConflict {
            source_id: None,
            path: key.to_string(),
            existing: "non-empty configuration key".to_string(),
            incoming: format!("empty key normalized from '{origin}'"),
        });
    }

    if key.contains('.') && key.split('.').any(str::is_empty) {
        return Err(ConfigError::KeyConflict {
            source_id: None,
            path: key.to_string(),
            existing: "valid dotted key path".to_string(),
            incoming: format!("malformed key normalized from '{origin}'"),
        });
    }

    Ok(())
}

/// Records a flattened source key and rejects duplicate normalized keys.
#[cfg(any(feature = "toml", feature = "yaml"))]
pub(crate) fn ensure_unique_flattened_key(seen: &mut HashSet<String>, key: &str) -> ConfigResult<()> {
    if seen.insert(key.to_string()) {
        return Ok(());
    }

    Err(ConfigError::KeyConflict {
        source_id: None,
        path: key.to_string(),
        existing: "previous flattened source key".to_string(),
        incoming: "duplicate flattened source key".to_string(),
    })
}
